// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prometej_persistance;

#nullable disable

namespace Prometej_persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20261005134702_SessionStamp")]
    partial class SessionStamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prometej_core.Models.efModels.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExploreMore")
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuizGameId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizGameId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Period", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TimeFrame")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Periods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Zaplovite u svijet davnina književnosti, od drevnih civilizacija antičke Grčke, drevnog Rima te najpoznatijih tragedija, komedija te epova",
                            Image = "antika.png",
                            Name = "Antika",
                            SortOrder = 1,
                            TimeFrame = "8. st. pr. Kr. – 5. st."
                        },
                        new
                        {
                            Id = 2,
                            Description = "Naučite više o mračnom i najduljem razdoblju književnosti, viteškim romanima, utjecaju crkve na književnost te najpoznatijim piscima tog doba",
                            Image = "srednji_vijek.png",
                            Name = "Srednji vijek",
                            SortOrder = 2,
                            TimeFrame = "5. – 15. st."
                        },
                        new
                        {
                            Id = 7,
                            Description = "Upoznajte Dantea, Petrarcu i Boccaccia te humaniste koji su, vraćajući se antici, čovjeka ponovno stavili u središte zanimanja.",
                            Name = "Humanizam i predrenesansa",
                            SortOrder = 3,
                            TimeFrame = "14. – 15. st."
                        },
                        new
                        {
                            Id = 3,
                            Description = "Otkrijte svijet renesansne književnosti, motiv čovjeka u središtu svemira, humanizam, te začeće romana kao književnog žanra",
                            Image = "renesansa.png",
                            Name = "Renesansa",
                            SortOrder = 4,
                            TimeFrame = "15. – 16. st."
                        },
                        new
                        {
                            Id = 8,
                            Description = "Zavirite u književnost kićenoga stila, kontrasta i prolaznosti: od Gundulićeva Osmana i Dubravke do Calderónova kazališta.",
                            Name = "Barok",
                            SortOrder = 5,
                            TimeFrame = "17. st."
                        },
                        new
                        {
                            Id = 9,
                            Description = "Otkrijte doba razuma, reda i strogih pravila, Molièreovih komedija i prosvjetiteljskih ideja koje su mijenjale Europu.",
                            Name = "Klasicizam",
                            SortOrder = 6,
                            TimeFrame = "17. – 18. st."
                        },
                        new
                        {
                            Id = 10,
                            Description = "Pratite kako osjećaji potiskuju razum: Goetheov Werther, Sturm und Drang i prvi nagovještaji romantizma.",
                            Name = "Predromantizam",
                            SortOrder = 7,
                            TimeFrame = "druga polovica 18. st."
                        },
                        new
                        {
                            Id = 5,
                            Description = "Osjetite romantizam, razdoblje koje obilježava osjećajnost, maštu, prirodu, fokus na pojedinca, njegovu impresiju i ekspresiju.",
                            Image = "romantizam.png",
                            Name = "Romantizam",
                            SortOrder = 8,
                            TimeFrame = "kraj 18. – sredina 19. st."
                        },
                        new
                        {
                            Id = 4,
                            Description = "Realizam obilježava realan opis svijeta. Fokus je na dugačkom i detaljnom opisu likova i prostora što donosi brojne zanimljivosti iz tog vremena.",
                            Image = "realizam.png",
                            Name = "Realizam",
                            SortOrder = 9,
                            TimeFrame = "druga polovica 19. st."
                        },
                        new
                        {
                            Id = 6,
                            Description = "Modernizam obilježava razdoblje estetike u književnosti, umjetnost radi same sebe. Zavirite u čari modernizma, njegove teme, motive i najpoznatije autore.",
                            Image = "modernizam.png",
                            Name = "Modernizam",
                            SortOrder = 10,
                            TimeFrame = "sredina 19. – početak 20. st."
                        },
                        new
                        {
                            Id = 11,
                            Description = "Uđite u književnost krika, pobune i slobodnoga stiha, uz A. B. Šimića, Kafku i ranoga Krležu.",
                            Name = "Ekspresionizam",
                            SortOrder = 11,
                            TimeFrame = "1910. – 1925."
                        },
                        new
                        {
                            Id = 12,
                            Description = "Istražite književnost nakon ekspresionizma: Krležine Glembajeve, egzistencijalizam i Camusova Stranca, Marinkovićeva Kiklopa i postmodernizam.",
                            Name = "Suvremena književnost",
                            SortOrder = 12,
                            TimeFrame = "od kraja 1920-ih do danas"
                        });
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.PeriodContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId")
                        .IsUnique();

                    b.ToTable("PeriodContents");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectOption")
                        .HasColumnType("integer");

                    b.Property<string>("ExploreMore")
                        .HasColumnType("text");

                    b.Property<string>("FirstAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FourthAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HintText")
                        .HasColumnType("text");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<string>("SecondAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThirdAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntryCode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("EntryCode")
                        .IsUnique();

                    b.HasIndex("PeriodId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.QuizGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePlayed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubmissionKey")
                        .HasColumnType("uuid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId", "SubmissionKey")
                        .IsUnique();

                    b.ToTable("QuizGames");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionStamp")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Answer", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prometej_core.Models.efModels.QuizGame", "QuizGame")
                        .WithMany("Answers")
                        .HasForeignKey("QuizGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("QuizGame");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.PeriodContent", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.Period", "Period")
                        .WithOne()
                        .HasForeignKey("Prometej_core.Models.efModels.PeriodContent", "PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Question", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Quiz", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prometej_core.Models.efModels.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId");

                    b.Navigation("Creator");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.QuizGame", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prometej_core.Models.efModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.QuizGame", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
