// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prometej_persistance;

#nullable disable

namespace Prometej_persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20261006110357_Sittings")]
    partial class Sittings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prometej_core.Models.efModels.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExploreMore")
                        .HasColumnType("text");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<int?>("Place")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuizGameId")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceTextId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizGameId");

                    b.HasIndex("SourceTextId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Period", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TimeFrame")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Periods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Zaplovite u književnost stare Grčke i Rima: od Homerovih epova i Sofoklovih tragedija do Plautovih komedija i Vergilijeve Eneide.",
                            Image = "antika.webp",
                            Name = "Antika",
                            SortOrder = 1,
                            TimeFrame = "8. st. pr. Kr. – 5. st."
                        },
                        new
                        {
                            Id = 2,
                            Description = "Upoznajte najdulje razdoblje europske književnosti: junačke epove i viteške romane, crkvena prikazanja i prve hrvatske spomenike pisane glagoljicom.",
                            Image = "srednji-vijek.webp",
                            Name = "Srednji vijek",
                            SortOrder = 2,
                            TimeFrame = "5. – 15. st."
                        },
                        new
                        {
                            Id = 7,
                            Description = "Upoznajte Dantea, Petrarcu i Boccaccia te humaniste koji su, vraćajući se antici, čovjeka ponovno stavili u središte zanimanja.",
                            Image = "humanizam-i-predrenesansa.webp",
                            Name = "Humanizam i predrenesansa",
                            SortOrder = 3,
                            TimeFrame = "14. – 15. st."
                        },
                        new
                        {
                            Id = 3,
                            Description = "Otkrijte književnost koja u središte stavlja čovjeka: Marulićevu Juditu, Držićeve komedije, Shakespeareova Hamleta i Cervantesova Don Quijotea.",
                            Image = "renesansa.webp",
                            Name = "Renesansa",
                            SortOrder = 4,
                            TimeFrame = "15. – 16. st."
                        },
                        new
                        {
                            Id = 8,
                            Description = "Zavirite u književnost kićenoga stila, kontrasta i prolaznosti: od Gundulićeva Osmana i Dubravke do Calderónova kazališta.",
                            Image = "barok.webp",
                            Name = "Barok",
                            SortOrder = 5,
                            TimeFrame = "17. st."
                        },
                        new
                        {
                            Id = 9,
                            Description = "Otkrijte doba razuma, reda i strogih pravila, Molièreovih komedija i prosvjetiteljskih ideja koje su mijenjale Europu.",
                            Image = "klasicizam.webp",
                            Name = "Klasicizam",
                            SortOrder = 6,
                            TimeFrame = "17. – 18. st."
                        },
                        new
                        {
                            Id = 10,
                            Description = "Pratite kako osjećaji potiskuju razum: Goetheov Werther, Sturm und Drang i prvi nagovještaji romantizma.",
                            Image = "predromantizam.webp",
                            Name = "Predromantizam",
                            SortOrder = 7,
                            TimeFrame = "druga polovica 18. st."
                        },
                        new
                        {
                            Id = 5,
                            Description = "Osjetite romantizam, razdoblje koje obilježava osjećajnost, maštu, prirodu, fokus na pojedinca, njegovu impresiju i ekspresiju.",
                            Image = "romantizam.webp",
                            Name = "Romantizam",
                            SortOrder = 8,
                            TimeFrame = "kraj 18. – sredina 19. st."
                        },
                        new
                        {
                            Id = 4,
                            Description = "Realizam obilježava realan opis svijeta. Fokus je na dugačkom i detaljnom opisu likova i prostora što donosi brojne zanimljivosti iz tog vremena.",
                            Image = "realizam.webp",
                            Name = "Realizam",
                            SortOrder = 9,
                            TimeFrame = "druga polovica 19. st."
                        },
                        new
                        {
                            Id = 6,
                            Description = "Modernizam obilježava razdoblje estetike u književnosti, umjetnost radi same sebe. Zavirite u čari modernizma, njegove teme, motive i najpoznatije autore.",
                            Image = "modernizam.webp",
                            Name = "Modernizam",
                            SortOrder = 10,
                            TimeFrame = "sredina 19. – početak 20. st."
                        },
                        new
                        {
                            Id = 11,
                            Description = "Uđite u književnost krika, pobune i slobodnoga stiha, uz A. B. Šimića, Kafku i ranoga Krležu.",
                            Image = "ekspresionizam.webp",
                            Name = "Ekspresionizam",
                            SortOrder = 11,
                            TimeFrame = "1910. – 1925."
                        },
                        new
                        {
                            Id = 12,
                            Description = "Istražite književnost nakon ekspresionizma: Krležine Glembajeve, egzistencijalizam i Camusova Stranca, Marinkovićeva Kiklopa i postmodernizam.",
                            Image = "suvremena-knjizevnost.webp",
                            Name = "Suvremena književnost",
                            SortOrder = 12,
                            TimeFrame = "od kraja 1920-ih do danas"
                        });
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.PeriodContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId")
                        .IsUnique();

                    b.ToTable("PeriodContents");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("jsonb");

                    b.Property<int?>("CorrectOption")
                        .HasColumnType("integer");

                    b.Property<string>("ExploreMore")
                        .HasColumnType("text");

                    b.Property<string>("FirstAnswer")
                        .HasColumnType("text");

                    b.Property<string>("FourthAnswer")
                        .HasColumnType("text");

                    b.Property<string>("HintText")
                        .HasColumnType("text");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<string>("SecondAnswer")
                        .HasColumnType("text");

                    b.Property<int?>("SourceTextId")
                        .HasColumnType("integer");

                    b.Property<string>("ThirdAnswer")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("choice");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("SourceTextId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntryCode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTest")
                        .HasColumnType("boolean");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("EntryCode")
                        .IsUnique();

                    b.HasIndex("PeriodId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.QuizGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePlayed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubmissionKey")
                        .HasColumnType("uuid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId", "SubmissionKey")
                        .IsUnique();

                    b.ToTable("QuizGames");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Reply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TopicId");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Sitting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("QuizGameId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TimeLimitEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("QuizGameId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("QuizId", "UserId")
                        .IsUnique()
                        .HasFilter("\"FinishedAt\" IS NULL");

                    b.ToTable("Sittings");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.SittingAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int[]>("Given")
                        .HasColumnType("integer[]");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int[]>("Shown")
                        .HasColumnType("integer[]");

                    b.Property<int>("SittingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SittingId");

                    b.ToTable("SittingAnswers");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.SourceText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("SourceTexts");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PeriodId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionStamp")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Answer", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prometej_core.Models.efModels.QuizGame", "QuizGame")
                        .WithMany("Answers")
                        .HasForeignKey("QuizGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prometej_core.Models.efModels.SourceText", null)
                        .WithMany()
                        .HasForeignKey("SourceTextId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Question");

                    b.Navigation("QuizGame");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.PeriodContent", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.Period", "Period")
                        .WithOne()
                        .HasForeignKey("Prometej_core.Models.efModels.PeriodContent", "PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Question", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prometej_core.Models.efModels.SourceText", "SourceText")
                        .WithMany()
                        .HasForeignKey("SourceTextId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Quiz");

                    b.Navigation("SourceText");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Quiz", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prometej_core.Models.efModels.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId");

                    b.Navigation("Creator");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.QuizGame", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prometej_core.Models.efModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Reply", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Prometej_core.Models.efModels.Topic", "Topic")
                        .WithMany("Replies")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Sitting", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.QuizGame", "QuizGame")
                        .WithOne("Sitting")
                        .HasForeignKey("Prometej_core.Models.efModels.Sitting", "QuizGameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Prometej_core.Models.efModels.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prometej_core.Models.efModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("QuizGame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.SittingAnswer", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prometej_core.Models.efModels.Sitting", "Sitting")
                        .WithMany("Answers")
                        .HasForeignKey("SittingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Sitting");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.SourceText", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.Quiz", "Quiz")
                        .WithMany("SourceTexts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Topic", b =>
                {
                    b.HasOne("Prometej_core.Models.efModels.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Prometej_core.Models.efModels.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("SourceTexts");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.QuizGame", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Sitting");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Sitting", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Prometej_core.Models.efModels.Topic", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
